package septchallenge;

import java.util.Arrays;

/*
389. Find the Difference
 Find the Difference
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */
public class FindtheDifference {
    public static void main(String[] args) {
        System.out.println(findTheDifference("a", "aa"));
    }

    public static char findTheDifference(String s, String t) {
        int[] alphabets = new int[26];

        alphabets[t.charAt(0) - 'a'] -= 1;
        for (int i = 1; i < t.length(); i++) {
            alphabets[s.charAt(i - 1) - 'a'] += 1;
            alphabets[t.charAt(i) - 'a'] -= 1;
        }

        for (int i = 0; i < alphabets.length; i++) {
            if (alphabets[i] != 0)
                return (char) (i + 'a');
        }


        return ' ';
    }

    public static char findTheDifferenceV2(String s, String t) {
        int[] alphabets = new int[26];
        int[] alphabets2 = new int[26];

        //char tempArray[] = t.toCharArray();
        //Arrays.sort(tempArray);
        alphabets2[t.charAt(0) - 'a'] += 1;
        for (int i = 1; i < t.length(); i++) {
            alphabets[s.charAt(i - 1) - 'a'] += 1;
            alphabets2[t.charAt(i) - 'a'] += 1;
        }

        for (int i = 0; i < alphabets.length; i++) {
            if (alphabets[i] != alphabets2[i]) {
                return (char) (i + 'a');
            }
        }

        return ' ';
    }
}
